version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: cloudbtech-leave-mysql
    restart: always
    ports:
      - "3310:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: cloudbtech_leavemanagement
      MYSQL_USER: cloudbtech_user
      MYSQL_PASSWORD: password
    volumes:
      - cloudbtech-mysql-data:/var/lib/mysql
    networks:
      - cloudbtech-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10

  app:
    image: ghandgevikas/leave-management:${DOCKER_TAG:-latest}
    container_name: cloudbtech-leave-app
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/cloudbtech_leavemanagement?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      SERVER_PORT: 8094
    networks:
      - cloudbtech-network
    restart: unless-stopped

  nginx:
    build: ./nginx
    container_name: cloudbtech-leave-nginx
    restart: unless-stopped
    ports:
      - "8084:80"
    depends_on:
      - app
    networks:
      - cloudbtech-network

networks:
  cloudbtech-network:
    driver: bridge

volumes:
  cloudbtech-mysql-data:
