version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: leave-management-mysql-Arcon
    restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: leavemanagement
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - leave-management-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10

  app:
    image: ghandgevikas/leave-management:${DOCKER_TAG:-latest}
    container_name: leave-management-app-Arcon
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8092:8090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/leavemanagement?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    networks:
      - leave-management-network
    restart: unless-stopped

networks:
  leave-management-network:
    driver: bridge

volumes:
  mysql-data:
